#!/bin/bash

while getopts ":m:c:p:t:" opt; do
  case $opt in
    m) mode="$OPTARG"
    ;;
    c) config="$OPTARG"
    ;;
    p) path="$OPTARG"
    ;;
    t) target="$OPTARG"
    ;;
  esac
done

# add t) (target: chloroplast,nucleus,mitochondrion,nucrdna), m) (extraction_targeted; extraction_untargeted)


## Help display of function
if [ "$1" == "-h" ]; then
    ##cat `dirname $0`/README.txt
  echo "Usage: `basename $0` [-h] [-m mode] [-c configfile.txt] [-p path]

____________________________________________________
   ___       _   _          ____  _  ___
' / _ \ _ __| |_| |__   ___/ ___|| |/ (_)_ __ ___  '
'| | | |  __| __|  _ \ / _ \___ \|   /| |  _   _  \'
'| |_| | |  | |_| | | | (_) |__) | . \| | | | | | |'
' \___/|_|   \__|_| |_|\___/____/|_|\_\_|_| |_| |_|'
____________________________________________________


OrthoSkim: Skimming of orthologous regions from shotgun sequencing
           where:
            -m (mode)  perform pipeline according to the choosen mode:
                  - [indexing] (make paramfile files)
                  - [SPAdes_assembly] (run SPAdes de novo assembly for each samples)
                  - [SPAdes_reformate] (reformates SPAdes output according to OrthoSkim pipeline)
                  - [extraction_targeted] (extraction of genes from targeted assemblies directly with
                                          annotations; target: chloroplast,nucrdna)
                  - [extraction_untargeted] (extraction of genes from non-targeted assemblies directly
                                            with mapping into references; target: chloroplast_CDS,chloroplast_rRNA,
                                            chloroplast_tRNA,nucleus,mitochondrion_CDS,mitochondrion_rRNA,mitochondrion_tRNA)
                  - [DB_mitochondrion] (make a database bank of mitochondrial genes from genbank annotations)
                  - [DB_chloroplast] (make a database bank of chloroplastic genes from genbank annotations)
                  - [stat_chloro] (output summary statistic for chloroplast assemblies)
                  - [stat_rdna] (output summary statistic for rdna assemblies)
                  - [stat_SPAdes] (check assemblies by generating summary statistics)
                  - [get_stat] (get statistics of gene extraction for files in -p {PATH} directory)
                  - [selection] (extract only interested taxa from gene extraction files)
            -c (config)  set the config file
            -t (target) cellular component to be extract:
                  - [chloroplast] (only for [extraction_targeted] mode. Extract all CDS+tRNA+rRNA genes)
                  - [nucrdna] (only for [extraction_targeted] mode. Extract all rRNA and Internal Transcribed Spacer)
                  - [nucleus] (extraction_untargeted)
                  - [chloroplast_CDS] (extraction_untargeted)
                  - [chloroplast_tRNA] (extraction_untargeted)
                  - [chloroplast_rRNA] (extraction_untargeted)
                  - [mitochondrion_CDS] (extraction_untargeted)
                  - [mitochondrion_tRNA] (extraction_untargeted)
                  - [mitochondrion_rRNA] (extraction_untargeted)
            -p (path)  set the path to get out statistic of gene extraction for [get_stat] mode / or for selection mode
            "
  exit 0
fi


## OrthoSkim process
source $config
source `dirname $0`/tools.sh

set -e

if [ ${VERBOSE} -eq 1 ]; then
      set -x
fi


echo "Processing OrthoSkim program"

mkdir -p ${RES}/${PATHNAME_ASSEMBLY}/Samples
mkdir -p ${RES}/Extraction

  if [ $mode == 'indexing' ]; then
		echo "INFO: mode=$mode - indexing of annotation files"
    echo "CMD: `dirname $0`/src/MakeParam.py -p ${PATH_FIND_CHLORO} -o ${RES}/${PATHNAME_ASSEMBLY}/ -cfind > ${LIST_FILES}"
		`dirname $0`/src/MakeParam.py -p ${PATH_FIND_CHLORO} -o ${RES}/${PATHNAME_ASSEMBLY}/ -cfind > ${LIST_FILES}
		echo "STATUS: done"
		exit 0


	elif [ $mode == 'SPAdes_reformate' ]; then
		echo "INFO: mode=$mode - preprocessing of assemblies files from SPAdes for nucleus/mitochondrion modes"
		while read f;
		do
			samplename=`echo ${f} | awk '{print $3}'`
      if [ -s ${RES}/${PATHNAME_ASSEMBLY}/${samplename}/scaffolds.fasta ]; then
        cp ${RES}/${PATHNAME_ASSEMBLY}/${samplename}/scaffolds.fasta ${RES}/${PATHNAME_ASSEMBLY}/Samples/${samplename}.fa
      else
        echo "WARN: $samplename unprocessed"
        continue
      fi
    done <${LIST_FILES}
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'SPAdes_assembly' ]; then
		echo "INFO: mode=$mode - SPAdes assembly run"
		while read f;
		do
			samplename=`echo ${f} | awk '{print $3}'`
			r1=`echo ${f} | awk '{print $4}'`
			r2=`echo ${f} | awk '{print $5}'`
			#outp=`echo ${f} | awk '{print $6}'`
      # if assembly_done existed
      if [ -s ${RES}/assembly_done.log ]; then
        # we checked if sample already in done.log to continue to another sample
        if grep -Fxq "${samplename}" ${RES}/assembly_done.log; then
          echo "WARN: $samplename already processed"
          continue
        else
          echo "${SPADES} -1 ${r1} -2 ${r2} --cov-cutoff auto -o ${RES}/${PATHNAME_ASSEMBLY}/${samplename} -t ${THREADS} -m ${MEMORY} -k ${KMER}"
          # we check if no error on function run
          if ${SPADES} -1 ${r1} -2 ${r2} --cov-cutoff auto -o ${RES}/${PATHNAME_ASSEMBLY}/${samplename} -t ${THREADS} -m ${MEMORY} -k ${KMER}; then
            echo $samplename >> ${RES}/assembly_done.log
          else
            echo $samplename >> ${RES}/assembly_error.log
          fi
        fi
      else
        echo "${SPADES} -1 ${r1} -2 ${r2} --cov-cutoff auto -o ${RES}/${PATHNAME_ASSEMBLY}/${samplename} -t ${THREADS} -m ${MEMORY} -k ${KMER}"
        if ${SPADES} -1 ${r1} -2 ${r2} --cov-cutoff auto -o ${RES}/${PATHNAME_ASSEMBLY}/${samplename} -t ${THREADS} -m ${MEMORY} -k ${KMER}; then
          echo ${samplename} >> ${RES}/assembly_done.log
        else
          echo ${samplename} >> ${RES}/assembly_error.log
        fi
      fi
		done <${LIST_FILES}
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'extraction_untargeted' ] && [ $target == 'nucleus' ]; then
		echo "INFO: mode=$mode - Extraction of nuclear genes from mapping assemblies into reference"
		mkdir -p ${RES}/Mapping/nucleus
		echo "*** make DIAMOND formatted reference database ***"
		refdb=${NUC_REF/.fasta/}
    echo "CMD: ${DIAMOND} makedb --in ${NUC_REF} -d ${refdb}"
		${DIAMOND} makedb --in ${NUC_REF} -d ${refdb} --threads ${THREADS}
		echo "*** mapping and extraction of assemblies into reference ***"
		for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
			lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/nucleus_done.log ]; then
        if grep -Fxq "${f}" ${RES}/nucleus_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/nucleus/matches_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
    			${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/nucleus/matches_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
    			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/nucleus/matches_${lib} | sort | uniq > ${RES}/Mapping/nucleus/hits_${lib}
          if [ -s ${RES}/Mapping/nucleus/hits_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/nucleus/hits_${lib} - > ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta
            echo "CMD: ${EXONERATE} --model protein2genome -q ${NUC_REF} -t ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/nucleus/out_${lib}.gff"
            if ${EXONERATE} --model protein2genome -q ${NUC_REF} -t ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/nucleus/out_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta -g ${RES}/Mapping/nucleus/out_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${NUC_TYPE} --threads ${THREADS} -s ${NUC_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta -g ${RES}/Mapping/nucleus/out_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${NUC_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${NUC_REF}
              rm ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta ${RES}/Mapping/nucleus/hits_${lib} ${RES}/Mapping/nucleus/matches_${lib}
        			echo ${f} >> ${RES}/nucleus_done.log
            else
              echo ${f} >> ${RES}/nucleus_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${NUC_REF} database"
            echo ${f} >> ${RES}/nucleus_error.log
            continue
          fi
        fi
      else
        echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/nucleus/matches_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
  			${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/nucleus/matches_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
  			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/nucleus/matches_${lib} | sort | uniq > ${RES}/Mapping/nucleus/hits_${lib}
        if [ -s ${RES}/Mapping/nucleus/hits_${lib} ]; then
          awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/nucleus/hits_${lib} - > ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta
          echo "CMD: ${EXONERATE} --model protein2genome -q ${NUC_REF} -t ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/nucleus/out_${lib}.gff"
          if ${EXONERATE} --model protein2genome -q ${NUC_REF} -t ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/nucleus/out_${lib}.gff; then
            echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta -g ${RES}/Mapping/nucleus/out_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${NUC_TYPE} --threads ${THREADS} -s ${NUC_REF}"
            `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta -g ${RES}/Mapping/nucleus/out_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${NUC_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${NUC_REF}
            rm ${RES}/Mapping/nucleus/contigs_hits_${lib}.fasta ${RES}/Mapping/nucleus/hits_${lib} ${RES}/Mapping/nucleus/matches_${lib}
      			echo ${f} >> ${RES}/nucleus_done.log
          else
            echo ${f} >> ${RES}/nucleus_error.log
          fi
        else
          echo "WARN: No hits were detected when mapping ${f} into ${NUC_REF} database"
          echo ${f} >> ${RES}/nucleus_error.log
          continue
        fi
      fi
		done
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'extraction_targeted' ] && [ $target == 'chloroplast' ]; then
		echo "INFO: mode=$mode - Extraction of chloroplastic genes from annotated files"
		while read f;
		do
			samplename=`echo ${f} | awk '{print $3}'`
			file=`echo ${f} | awk '{print $1}'`
      if [ -s ${RES}/chloroplast_done.log ]; then
        if grep -Fxq "${file}" ${RES}/chloroplast_done.log; then
          echo "WARN: $file already processed"
          continue
        else
          echo "CMD: `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m \"chloroplast\" -g ${CHLORO_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}"
    			if `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m "chloroplast" -g ${CHLORO_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}; then
            echo $file >> ${RES}/chloroplast_done.log
          else
            echo $file >> ${RES}/chloroplast_error.log
          fi
        fi
      else
        echo "CMD: `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m \"chloroplast\" -g ${CHLORO_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}"
  			if `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m "chloroplast" -g ${CHLORO_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}; then
          echo $file >> ${RES}/chloroplast_done.log
        else
          echo $file >> ${RES}/chloroplast_error.log
        fi
      fi
		done <${LIST_FILES}
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'extraction_targeted' ] && [ $target == 'nucrdna' ]; then
		echo "INFO: mode=$mode - Extraction of nuclear rDNA genes from annotated files"
		while read f;
		do
			samplename=`echo ${f} | awk '{print $3}'`
			file=`echo ${f} | awk '{print $1}' | perl -pe 's/.chloro.embl/.rdnanuc.embl/'`
      if [ -s ${RES}/nucrdna_done.log ]; then
        if grep -Fxq "${file}" ${RES}/nucrdna_done.log; then
          echo "WARN: $file already processed"
          continue
        else
          echo "CMD: `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m \"nucrdna\" -g ${NRDNA_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}"
          if `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m "nucrdna" -g ${NRDNA_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}; then
            echo ${file} >> ${RES}/nucrdna_done.log
          else
            echo ${file} >> ${RES}/nucrdna_error.log
          fi
        fi
      else
        echo "CMD: `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m \"nucrdna\" -g ${NRDNA_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}"
        if `dirname $0`/src/AnoSamp_threads.py -t ${file} -n ${samplename} -m "nucrdna" -g ${NRDNA_GENES} -fmt ${ANNOFMT} -o ${RES}/Extraction/ --threads ${THREADS}; then
          echo ${file} >> ${RES}/nucrdna_done.log
        else
          echo ${file} >> ${RES}/nucrdna_error.log
        fi
      fi
		done <${LIST_FILES}
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'DB_mitochondrion' ]; then
		echo "INFO: mode=$mode - Creation of mitochondrial database from genbank annotations for CDS, tRNA and rRNA features"
		mkdir -p ${RES}/references/unclean
    echo '*** extraction of all genes from annotations ***'
    echo "CMD: `dirname $0`/src/AnoRef_mito.py --single -in ${MITO_GENBANK} -o ${RES}/references/unclean -m mitochondrion -fmt genbank"
		`dirname $0`/src/AnoRef_mito.py --single -in ${MITO_GENBANK} -o ${RES}/references/unclean -m mitochondrion -fmt genbank

		echo '*** alignment of CDS into mito seeds, and extraction of final CDS of reference ***'
		for file in `find ${RES}/references/unclean/mitochondrion_CDS/ -type f -name \*.fa`;
		do
      echo "CMD: ${EXONERATE} -q ${SEEDS_MITO_CDS} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate"
			${EXONERATE} -q ${SEEDS_MITO_CDS} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate
      echo "CMD: `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_CDS} -g ${RES}/references/tmp.exonerate -m mitochondrion_CDS -o ${RES}/references/clean --threads ${THREADS}"
      `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_CDS} -g ${RES}/references/tmp.exonerate -m mitochondrion_CDS -o ${RES}/references/clean --threads ${THREADS}
		done
		cat ${RES}/references/clean/mitochondrion_CDS/*.fa > ${MITO_REF_CDS}
		echo "STATUS: done"

    echo '*** alignment of rRNA into mito seeds, and extraction of final rRNA of reference ***'
		for file in `find ${RES}/references/unclean/mitochondrion_rRNA/ -type f -name \*.fa`;
		do
      echo "CMD: ${EXONERATE} -q ${SEEDS_MITO_rRNA} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate"
			${EXONERATE} -q ${SEEDS_MITO_rRNA} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate
      echo "CMD: `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_rRNA} -g ${RES}/references/tmp.exonerate -m mitochondrion_rRNA -o ${RES}/references/clean --threads ${THREADS}"
      `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_rRNA} -g ${RES}/references/tmp.exonerate -m mitochondrion_rRNA -o ${RES}/references/clean --threads ${THREADS}
		done
		cat ${RES}/references/clean/mitochondrion_rRNA/*.fa > ${MITO_REF_rRNA}
		echo "STATUS: done"

    echo '*** alignment of tRNA into mito seeds, and extraction of final tRNA of reference ***'
		for file in `find ${RES}/references/unclean/mitochondrion_tRNA/ -type f -name \*.fa`;
		do
      echo "CMD: ${EXONERATE} -q ${SEEDS_MITO_tRNA} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate"
			${EXONERATE} -q ${SEEDS_MITO_tRNA} -t ${file} --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | gawk '!/^Hostname:|^Command line:|^-- completed exonerate analysis/ {print $0}' > ${RES}/references/tmp.exonerate
      echo "CMD: `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_tRNA} -g ${RES}/references/tmp.exonerate -m mitochondrion_tRNA -o ${RES}/references/clean --threads ${THREADS}"
      `dirname $0`/src/ExoGFF_ref.py -i ${file} -s ${SEEDS_MITO_tRNA} -g ${RES}/references/tmp.exonerate -m mitochondrion_tRNA -o ${RES}/references/clean --threads ${THREADS}
		done
		cat ${RES}/references/clean/mitochondrion_tRNA/*.fa > ${MITO_REF_tRNA}
		echo "STATUS: done"

		exit 0

  elif [ $mode == 'DB_chloroplast' ]; then
    echo "INFO: mode=$mode - Creation of chloroplastic database from phyloskims annotations for CDS, tRNA and rRNA features"
    mkdir -p ${RES}/references/clean
    while read f;
		do
			file=`echo ${f} | awk '{print $1}'`
      if [ -s ${RES}/references/chloroplast_done.log ]; then
        if grep -Fxq "${file}" ${RES}/references/chloroplast_done.log; then
          echo "WARN: $file already processed"
          continue
        else
          echo "CMD: `dirname $0`/src/AnoRef_others.py -i ${file} -m chloroplast -g ${CHLORO_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}"
    			if `dirname $0`/src/AnoRef_others.py -i ${file} -m chloroplast -g ${CHLORO_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}; then
            echo $file >> ${RES}/references/chloroplast_done.log
          else
            echo $file >> ${RES}/references/chloroplast_error.log
          fi
        fi
      else
        echo "CMD: `dirname $0`/src/AnoRef_others.py -i ${file} -m chloroplast -g ${CHLORO_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}"
  			if `dirname $0`/src/AnoRef_others.py -i ${file} -m chloroplast -g ${CHLORO_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}; then
          echo $file >> ${RES}/references/chloroplast_done.log
        else
          echo $file >> ${RES}/references/chloroplast_error.log
        fi
      fi
		done <${LIST_FILES}
    cat ${RES}/references/clean/chloroplast_CDS/*.fa > ${CHLORO_REF_CDS}
    cat ${RES}/references/clean/chloroplast_tRNA/*.fa > ${CHLORO_REF_tRNA}
    cat ${RES}/references/clean/chloroplast_rRNA/*.fa > ${CHLORO_REF_rRNA}
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'DB_nucrdna' ]; then
    echo "INFO: mode=$mode - Creation of nucrdna database from phyloskims annotations for CDS, tRNA and rRNA features"
    mkdir -p ${RES}/references/clean
    while read f;
    do
      file=`echo ${f} | awk '{print $1}' | perl -pe 's/.chloro.embl/.rdnanuc.embl/'
      if [ -s ${RES}/references/nucrdna_done.log ]; then
        if grep -Fxq "${file}" ${RES}/references/nucrdna_done.log; then
          echo "WARN: $file already processed"
          continue
        else
          echo "CMD: `dirname $0`/src/AnoRef_others.py -i ${file} -m nucrdna -g ${NRDNA_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}"
          if `dirname $0`/src/AnoRef_others.py -i ${file} -m nucrdna -g ${NRDNA_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}; then
            echo $file >> ${RES}/references/nucrdna_done.log
          else
            echo $file >> ${RES}/references/nucrdna_error.log
          fi
        fi
      else
        echo "CMD: `dirname $0`/src/AnoRef_others.py -i ${file} -m nucrdna -g ${NRDNA_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}"
        if `dirname $0`/src/AnoRef_others.py -i ${file} -m nucrdna -g ${NRDNA_GENES} -fmt embl -o ${RES}/references/clean --threads ${THREADS}; then
          echo $file >> ${RES}/references/nucrdna_done.log
        else
          echo $file >> ${RES}/references/nucrdna_error.log
        fi
      fi
    done <${LIST_FILES}
    cat ${RES}/references/clean/nucrdna_misc_RNA/*.fa > ${NRDNA_REF_misc_RNA}
    cat ${RES}/references/clean/nucrdna_rRNA/*.fa > ${NRDNA_REF_rRNA}
    echo "STATUS: done"
    exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'mitochondrion_rRNA' ]; then
    echo 'INFO: mode=$mode - Extraction of mitchondrial rRNA from non targeted assemblies (SPADes assembly)'
    mkdir -p ${RES}/Mapping/mitochondrion
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
      lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/mitochondrion_rRNA_done.log ]; then
        if grep -Fxq "${f}" ${RES}/mitochondrion_rRNA_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_rRNA} --gene_type rRNA --compartment mitochondrion
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_rRNA} --gene_type rRNA --compartment mitochondrion
            else
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_rRNA} --update --gene_type rRNA --compartment mitochondrion
            fi
          fi
          CLOSED_REF=${RES}/references/closed_mitochondrion_rRNA.fa
          if [ -s ${CLOSED_REF} ]; then
            echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
            ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
      			${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_rRNA_${lib}
            if [ -s ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta
              echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff"
              if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} ${RES}/Mapping/mitochondrion/matches_rRNA_${lib}
                echo ${f} >> ${RES}/mitochondrion_rRNA_done.log
              else
                echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_rRNA} --gene_type rRNA --compartment mitochondrion
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_rRNA} --gene_type rRNA --compartment mitochondrion
          else
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_rRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_rRNA} --update --gene_type rRNA --compartment mitochondrion
          fi
        fi
        CLOSED_REF=${RES}/references/closed_mitochondrion_rRNA.fa
        if [ -s ${CLOSED_REF} ]; then
          echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
          ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
          ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_rRNA_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_rRNA_${lib}
          if [ -s ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta
            echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff"
            if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/mitochondrion/contigs_hits_rRNA_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_rRNA_${lib} ${RES}/Mapping/mitochondrion/matches_rRNA_${lib}
              echo ${f} >> ${RES}/mitochondrion_rRNA_done.log
            else
              echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/mitochondrion_rRNA_error.log
          continue
        fi
      fi
    done
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'mitochondrion_tRNA' ]; then
    echo 'INFO: mode=$mode - Extraction of mitchondrial tRNA from non targeted assemblies (SPADes assembly)'
    mkdir -p ${RES}/Mapping/mitochondrion
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
      lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/mitochondrion_tRNA_done.log ]; then
        if grep -Fxq "${f}" ${RES}/mitochondrion_tRNA_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_tRNA} --gene_type tRNA --compartment mitochondrion
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_tRNA} --gene_type tRNA --compartment mitochondrion
            else
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_tRNA} --update --gene_type tRNA --compartment mitochondrion
            fi
          fi
          CLOSED_REF=${RES}/references/closed_mitochondrion_tRNA.fa
          if [ -s ${CLOSED_REF} ]; then
            echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
            ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
      			${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_tRNA_${lib}
            if [ -s ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta
              echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff"
              if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} ${RES}/Mapping/mitochondrion/matches_tRNA_${lib}
                echo ${f} >> ${RES}/mitochondrion_tRNA_done.log
              else
                echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_tRNA} --gene_type tRNA --compartment mitochondrion
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_tRNA} --gene_type tRNA --compartment mitochondrion
          else
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_tRNA} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_tRNA} --update --gene_type tRNA --compartment mitochondrion
          fi
        fi
        CLOSED_REF=${RES}/references/closed_mitochondrion_tRNA.fa
        if [ -s ${CLOSED_REF} ]; then
          echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
          ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
          ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_tRNA_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_tRNA_${lib}
          if [ -s ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta
            echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff"
            if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/mitochondrion/contigs_hits_tRNA_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_tRNA_${lib} ${RES}/Mapping/mitochondrion/matches_tRNA_${lib}
              echo ${f} >> ${RES}/mitochondrion_tRNA_done.log
            else
              echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/mitochondrion_tRNA_error.log
          continue
        fi
      fi
    done
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'mitochondrion_CDS' ]; then
    echo 'INFO: mode=$mode - Extraction of mitchondrial CDS from non targeted assemblies (SPADes assembly)'
    mkdir -p ${RES}/Mapping/mitochondrion
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
      lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/mitochondrion_CDS_done.log ]; then
        if grep -Fxq "${f}" ${RES}/mitochondrion_CDS_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_CDS} --gene_type CDS --compartment mitochondrion
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_CDS} --gene_type CDS --compartment mitochondrion
            else
              `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_CDS} --update --gene_type CDS --compartment mitochondrion
            fi
          fi
          CLOSED_REF=${RES}/references/closed_mitochondrion_CDS.fa
          if [ -s ${CLOSED_REF} ]; then
            refdb=${CLOSED_REF/.fa/}
            echo "CMD: ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb}"
        		${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb} --threads ${THREADS}
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/mitochondrion/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
      			${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/mitochondrion/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_CDS_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_CDS_${lib}
            if [ -s ${RES}/Mapping/mitochondrion/hits_CDS_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_CDS_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta
              echo "CMD: ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff"
              if ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_CDS_${lib} ${RES}/Mapping/mitochondrion/matches_CDS_${lib}
                echo ${f} >> ${RES}/mitochondrion_CDS_done.log
              else
                echo ${f} >> ${RES}/mitochondrion_CDS_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/mitochondrion_CDS_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_CDS_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_MITO_CDS} --gene_type CDS --compartment mitochondrion
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_CDS} --gene_type CDS --compartment mitochondrion
          else
            `dirname $0`/src/ExtractRef_name.py -in ${MITO_REF_CDS} -g ${MITO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_MITO_CDS} --update --gene_type CDS --compartment mitochondrion
          fi
        fi
        CLOSED_REF=${RES}/references/closed_mitochondrion_CDS.fa
        if [ -s ${CLOSED_REF} ]; then
          refdb=${CLOSED_REF/.fa/}
          echo "CMD: ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb}"
          ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb} --threads ${THREADS}
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/mitochondrion/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
          ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/mitochondrion/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/mitochondrion/matches_CDS_${lib} | sort | uniq > ${RES}/Mapping/mitochondrion/hits_CDS_${lib}
          if [ -s ${RES}/Mapping/mitochondrion/hits_CDS_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/mitochondrion/hits_CDS_${lib} - > ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta
            echo "CMD: ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff"
            if ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/mitochondrion/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/mitochondrion/contigs_hits_CDS_${lib}.fasta ${RES}/Mapping/mitochondrion/hits_CDS_${lib} ${RES}/Mapping/mitochondrion/matches_CDS_${lib}
              echo ${f} >> ${RES}/mitochondrion_CDS_done.log
            else
              echo ${f} >> ${RES}/mitochondrion_CDS_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/mitochondrion_CDS_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/mitochondrion_CDS_error.log
          continue
        fi
      fi
		done
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'stat_chloro' ]; then
		echo "INFO: mode=$mode - Summary statistics of chloroplast assemblies"
		${QUAST} `awk '{print $1}' ${LIST_FILES} | perl -pe 's/.embl/.fasta/'  | perl -pe 's/\n/ /'` -o ${RES}/report_chloro_assemblies
		rm -rf ${RES}/report_chloro_assemblies/basic_stats/
		#rm -rf ${RES}/report_chloro_assemblies/icarus_viewers/
		rm ${RES}/report_chloro_assemblies/report.tex ${RES}/report_chloro_assemblies/report.tsv ${RES}/report_chloro_assemblies/report.txt ${RES}/report_chloro_assemblies/transposed_report.tex ${RES}/report_chloro_assemblies/transposed_report.tsv
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'stat_rdna' ]; then
		echo "INFO: mode=$mode - Summary statistics of rdna assemblies"
		${QUAST} `awk '{print $1}' ${LIST_FILES} | perl -pe 's/.chloro.embl/.rdnanuc.fasta/'  | perl -pe 's/\n/ /'` -o ${RES}/report_rdnanuc_assemblies
		rm -rf ${RES}/report_rdnanuc_assemblies/basic_stats/
		#rm -rf ${RES}/report_rdnanuc_assemblies/icarus_viewers/
		rm ${RES}/report_rdnanuc_assemblies/report.tex ${RES}/report_rdnanuc_assemblies/report.tsv ${RES}/report_rdnanuc_assemblies/report.txt ${RES}/report_rdnanuc_assemblies/transposed_report.tex ${RES}/report_rdnanuc_assemblies/transposed_report.tsv
		echo "STATUS: done"
		exit 0

	elif [ $mode == 'stat_SPAdes' ]; then
		echo "INFO: mode=$mode - Summary statistics of nuclear assemblies"
		${QUAST} ${RES}/${PATHNAME_ASSEMBLY}/Samples/*.fa -o ${RES}/report_SPAdes_assemblies
		rm -rf ${RES}/report_SPAdes_assemblies/basic_stats/
		#rm -rf ${RES}/report_SPAdes_assemblies/icarus_viewers/
		rm ${RES}/report_SPAdes_assemblies/report.tex ${RES}/report_SPAdes_assemblies/report.tsv ${RES}/report_SPAdes_assemblies/report.txt ${RES}/report_SPAdes_assemblies/transposed_report.tex ${RES}/report_SPAdes_assemblies/transposed_report.tsv
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'get_stat' ]; then
    echo "INFO: mode=$mode - Statistics of genes extraction according to given path"
    echo "CMD: `dirname $0`/src/ExoStat.py -p $path -pfind > $path/report.log"
    `dirname $0`/src/ExoStat.py -p $path -pfind > $path/report.log
    echo "STATUS: done"
    exit 0

  elif [ $mode == 'selection' ]; then
    echo "INFO: mode=$mode - Selection of taxa from genes extraction"
    echo "CMD: `dirname $0`/src/SelecTaxa.py --inpath $path --pathfind --outpath ${RES}/Selection -t ${TAXALIST} -e ${EXTENSION} --threads ${THREADS}"
    `dirname $0`/src/SelecTaxa.py --inpath $path --pathfind --outpath ${RES}/Selection -t ${TAXALIST} -e ${EXTENSION} --threads ${THREADS}
    echo "STATUS: done"
    exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'chloroplast_rRNA' ]; then
		echo 'INFO: mode=$mode - Extraction of chloroplastic rRNA from assemblies'
		mkdir -p ${RES}/Mapping/chloroplast
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
			lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/chloroplast_rRNA_done.log ]; then
        if grep -Fxq "${f}" ${RES}/chloroplast_rRNA_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_rRNA} --gene_type rRNA --compartment chloroplast
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_rRNA} --gene_type rRNA --compartment chloroplast
            else
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_rRNA} --update --gene_type rRNA --compartment chloroplast
            fi
          fi
          CLOSED_REF=${RES}/references/closed_chloroplast_rRNA.fa
          if [ -s ${CLOSED_REF} ]; then
            echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
            ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
      			${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_rRNA_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_rRNA_${lib}
            if [ -s ${RES}/Mapping/chloroplast/hits_rRNA_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_rRNA_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta
              echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff"
              if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta ${RES}/Mapping/chloroplast/hits_rRNA_${lib} ${RES}/Mapping/chloroplast/matches_rRNA_${lib}
                echo ${f} >> ${RES}/chloroplast_rRNA_done.log
              else
                echo ${f} >> ${RES}/chloroplast_rRNA_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/chloroplast_rRNA_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_rRNA_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_rRNA} --gene_type rRNA --compartment chloroplast
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_rRNA} --gene_type rRNA --compartment chloroplast
          else
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_rRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_rRNA} --update --gene_type rRNA --compartment chloroplast
          fi
        fi
        CLOSED_REF=${RES}/references/closed_chloroplast_rRNA.fa
        if [ -s ${CLOSED_REF} ]; then
          echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
          ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
          ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_rRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_rRNA_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_rRNA_${lib}
          if [ -s ${RES}/Mapping/chloroplast/hits_rRNA_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_rRNA_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta
            echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff"
            if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_rRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/chloroplast/contigs_hits_rRNA_${lib}.fasta ${RES}/Mapping/chloroplast/hits_rRNA_${lib} ${RES}/Mapping/chloroplast/matches_rRNA_${lib}
              echo ${f} >> ${RES}/chloroplast_rRNA_done.log
            else
              echo ${f} >> ${RES}/chloroplast_rRNA_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_rRNA_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/chloroplast_rRNA_error.log
          continue
        fi
      fi
		done
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'chloroplast_tRNA' ]; then
		echo 'INFO: mode=$mode - Extraction of chloroplastic tRNA from assemblies'
		mkdir -p ${RES}/Mapping/chloroplast
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
			lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/chloroplast_tRNA_done.log ]; then
        if grep -Fxq "${f}" ${RES}/chloroplast_tRNA_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_tRNA} --gene_type tRNA --compartment chloroplast
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_tRNA} --gene_type tRNA --compartment chloroplast
            else
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_tRNA} --update --gene_type tRNA --compartment chloroplast
            fi
          fi
          CLOSED_REF=${RES}/references/closed_chloroplast_tRNA.fa
          if [ -s ${CLOSED_REF} ]; then
            echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
            ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
      			${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_rRNA_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_rRNA_${lib}
            if [ -s ${RES}/Mapping/chloroplast/hits_tRNA_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_tRNA_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta
              echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff"
              if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta ${RES}/Mapping/chloroplast/hits_tRNA_${lib} ${RES}/Mapping/chloroplast/matches_tRNA_${lib}
                echo ${f} >> ${RES}/chloroplast_tRNA_done.log
              else
                echo ${f} >> ${RES}/chloroplast_tRNA_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/chloroplast_tRNA_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_tRNA_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_tRNA} --gene_type tRNA --compartment chloroplast
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_tRNA} --gene_type tRNA --compartment chloroplast
          else
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_tRNA} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_tRNA} --update --gene_type tRNA --compartment chloroplast
          fi
        fi
        CLOSED_REF=${RES}/references/closed_chloroplast_tRNA.fa
        if [ -s ${CLOSED_REF} ]; then
          echo "CMD: ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl"
          ${BLASTDB} -in ${CLOSED_REF} -dbtype nucl
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7"
          ${BLASTN} -db ${CLOSED_REF} -query ${f} -out ${RES}/Mapping/chloroplast/matches_tRNA_${lib} -evalue ${EVALUE} -num_threads ${THREADS} -outfmt 7
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_tRNA_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_tRNA_${lib}
          if [ -s ${RES}/Mapping/chloroplast/hits_tRNA_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_tRNA_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta
            echo "CMD: ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff"
            if ${EXONERATE} --model genome2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_tRNA_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${CHLORO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/chloroplast/contigs_hits_tRNA_${lib}.fasta ${RES}/Mapping/chloroplast/hits_tRNA_${lib} ${RES}/Mapping/chloroplast/matches_tRNA_${lib}
              echo ${f} >> ${RES}/chloroplast_tRNA_done.log
            else
              echo ${f} >> ${RES}/chloroplast_tRNA_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_tRNA_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/chloroplast_tRNA_error.log
          continue
        fi
      fi
		done
		echo "STATUS: done"
		exit 0

  elif [ $mode == 'extraction_untargeted' ] && [ $target == 'chloroplast_CDS' ]; then
		echo 'INFO: mode=$mode - Extraction of chloroplastic CDS from assemblies'
		mkdir -p ${RES}/Mapping/chloroplast
    mkdir -p ${RES}/references
    for f in `find ${RES}/${PATHNAME_ASSEMBLY}/Samples/ -type f -name \*.fa`;
		do
			lib=`basename $f | perl -pe 's/.fa//'`
      if [ -s ${RES}/chloroplast_CDS_done.log ]; then
        if grep -Fxq "${f}" ${RES}/chloroplast_CDS_done.log; then
          echo "WARN: $f already processed"
          continue
        else
          echo "*** make formatted reference on the closest taxa from the database ***"
          if [ ${MODE_REF} == "distance" ]; then
            echo "CMD: `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast"
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} -s ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast
          else
            if [ ${TAXONOMY_UPDATE} == "no" ]; then
              echo "CMD: `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast"
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast
            else
              echo "CMD: `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_CDS} --update --gene_type CDS --compartment chloroplast"
              `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -s ${SEEDS_CHLORO_CDS} --update --gene_type CDS --compartment chloroplast
            fi
          fi
          CLOSED_REF=${RES}/references/closed_chloroplast_CDS.fa
          if [ -s ${CLOSED_REF} ]; then
            refdb=${CLOSED_REF/.fa/}
        		echo "*** make DIAMOND formatted reference database ***"
            echo "CMD: ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb}"
        		${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb} --threads ${THREADS}
            echo "*** mapping and extraction of assemblies into reference ***"
            echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/chloroplast/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
      			${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/chloroplast/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
      			awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_CDS_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_CDS_${lib}
            if [ -s ${RES}/Mapping/chloroplast/hits_CDS_${lib} ]; then
              awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_CDS_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta
              echo "CMD: ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff"
              if ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff; then
                echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
                `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
                rm ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta ${RES}/Mapping/chloroplast/hits_CDS_${lib} ${RES}/Mapping/chloroplast/matches_CDS_${lib}
                echo ${f} >> ${RES}/chloroplast_CDS_done.log
              else
                echo ${f} >> ${RES}/chloroplast_CDS_error.log
              fi
            else
              echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
              echo ${f} >> ${RES}/chloroplast_CDS_error.log
              continue
            fi
          else
            echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_CDS_error.log
            continue
          fi
        fi
      else
        echo "*** make formatted reference on the closest taxa from the database ***"
        if [ ${MODE_REF} == "distance" ]; then
          echo "CMD:  `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} --seeds ${SEEDS_CHLORO_CDS} -d ${DISTANCE_MATRIX} --gene_type CDS --compartment chloroplast"
          `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} -d ${DISTANCE_MATRIX} --seeds ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast
        else
          if [ ${TAXONOMY_UPDATE} == "no" ]; then
            echo "CMD: `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} --seeds ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast"
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} --seeds ${SEEDS_CHLORO_CDS} --gene_type CDS --compartment chloroplast
          else
            echo "CMD: `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} --seeds ${SEEDS_CHLORO_CDS} --update --gene_type CDS --compartment chloroplast"
            `dirname $0`/src/ExtractRef_name.py -in ${CHLORO_REF_CDS} -g ${CHLORO_GENES} -q ${lib} -o ${RES}/references/ -m ${MODE_REF} --seeds ${SEEDS_CHLORO_CDS} --update --gene_type CDS --compartment chloroplast
          fi
        fi
        CLOSED_REF=${RES}/references/closed_chloroplast_CDS.fa
        if [ -s ${CLOSED_REF} ]; then
          refdb=${CLOSED_REF/.fa/}
          echo "*** make DIAMOND formatted reference database ***"
          echo "CMD: ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb}"
          ${DIAMOND} makedb --in ${CLOSED_REF} -d ${refdb} --threads ${THREADS}
          echo "*** mapping and extraction of assemblies into reference ***"
          echo "CMD: ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/chloroplast/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive"
          ${DIAMOND} blastx --outfmt 6 qseqid sseqid pident length mismatch gapopen qframe qstart qend sstart send evalue bitscore slen -d ${refdb} -q ${f} -o ${RES}/Mapping/chloroplast/matches_CDS_${lib} --evalue ${EVALUE} --threads ${THREADS} --sensitive
          awk '{split($1,a,"_")}{if(a[6]>='"${COVERAGE}"' && a[4]>='"${MINCONTLENGTH}"') print $1}' ${RES}/Mapping/chloroplast/matches_CDS_${lib} | sort | uniq > ${RES}/Mapping/chloroplast/hits_CDS_${lib}
          if [ -s ${RES}/Mapping/chloroplast/hits_CDS_${lib} ]; then
            awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' $f | perl -pe 's@>@@' | awk ' NR==FNR {a[$1]=$1;next} {if($1 in a) {print ">"$1"\n"$NF}}' ${RES}/Mapping/chloroplast/hits_CDS_${lib} - > ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta
            echo "CMD: ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff"
            if ${EXONERATE} --model protein2genome -q ${CLOSED_REF} -t ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta --showquerygff yes --showtargetgff yes --showvulgar no --showcigar no --showalignment no | awk '!/^Hostname:|^Command line:|^-- completed exonerate analysis|#/ {print $0}' > ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff; then
              echo "CMD: `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} --threads ${THREADS} -s ${CLOSED_REF}"
              `dirname $0`/src/ExoGFF_threads.py -i ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta -g ${RES}/Mapping/chloroplast/out_CDS_${lib}.gff -m ${target} -o ${RES}/Extraction/ -n ${lib} -l ${MINLENGTH} -t ${MITO_TYPE} -c ${COVERAGE} -cl ${MINCONTLENGTH} --threads ${THREADS} -s ${CLOSED_REF}
              rm ${RES}/Mapping/chloroplast/contigs_hits_CDS_${lib}.fasta ${RES}/Mapping/chloroplast/hits_CDS_${lib} ${RES}/Mapping/chloroplast/matches_CDS_${lib}
              echo ${f} >> ${RES}/chloroplast_CDS_done.log
            else
              echo ${f} >> ${RES}/chloroplast_CDS_error.log
            fi
          else
            echo "WARN: No hits were detected when mapping ${f} into ${CLOSED_REF} database"
            echo ${f} >> ${RES}/chloroplast_CDS_error.log
            continue
          fi
        else
          echo "WARN: error to extract closed sequences into ${CLOSED_REF} database"
          echo ${f} >> ${RES}/chloroplast_CDS_error.log
          continue
        fi
      fi
		done
		echo "STATUS: done"
		exit 0

	fi

exit 0
